apiVersion: v1
kind: Pod
metadata:
  name: kubeo
  namespace:
  labels:
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
        readOnly: true
  volumes:
    - name: html
      gitRepo:
        repository: https://github.com/kalise/kubeo-website.git
        revision: master
        directory: .
